# Pandas for AI/ML – Conceptual & Technical Assessment

**Student:** Sravya Arege  
**Submission filename:** `sravya_Pandas.ipynb`

# Section A – Output Prediction

## Q1. Array Operations and Vectorization

In [5]:
import numpy as np
import pandas as pd

# Create the two structures with the same values.
arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64


**Explanation:** Both perform element-wise multiplication. The NumPy array stores the numerical values directly, while the Pandas Series also carries an index.

## Q2. Boolean Filtering

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

# Keep students whose marks are at least 65.
result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])
print("Rows:", result.shape[0])
print("Columns:", result.shape[1])

  Student  Marks
1       B     80
2       C     65
3       D     90
Rows: 3
Columns: 2


**Explanation:** Boolean filtering keeps only rows where the condition is True. The result has three rows and two columns.

## Q3. Descriptive Statistics

In [7]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print("Mean:", df['Marks'].mean())
print("Maximum:", df['Marks'].max())
print("Median:", df['Marks'].median())

Mean: 30.0
Maximum: 50
Median: 30.0


**Explanation:** Mean is the arithmetic average, maximum is the largest value, and median is the middle value after sorting.

## Q4. Group-wise Analysis

In [8]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

# Group salaries by department and calculate the average for each group.
department_average = df.groupby('Department')['Salary'].mean()

print(department_average)

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


**Explanation:** `groupby()` creates one group for each department, and `mean()` calculates the department-wise average salary.

## Q5. Pandas Correlation – Positive

In [9]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

# Measure the linear relationship between Hours and Marks.
correlation = df['Hours'].corr(df['Marks'])

print("Correlation:", correlation)

Correlation: 1.0


**Explanation:** The coefficient is 1.0, which indicates a perfect positive linear relationship.

## Q6. Pandas Correlation – Negative

In [10]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

# Measure the linear relationship between Price and Demand.
correlation = df['Price'].corr(df['Demand'])

print("Correlation:", correlation)

Correlation: -1.0


**Explanation:** The coefficient is -1.0, which indicates a perfect negative linear relationship.

# Section B – Code Correction

## Q1. CSV Header Handling

In [11]:
import pandas as pd
from io import StringIO

# Example of the supplied CSV structure: the first row contains column names.
csv_data = '''Student,Marks
A,75
B,82
C,91'''

# Use the existing first row as the header instead of treating it as data.
df = pd.read_csv(StringIO(csv_data), header=0)

print(df)

  Student  Marks
0       A     75
1       B     82
2       C     91


**Issue:** `header=None` tells Pandas that there is no header.  
**Correction:** Use the first row as the header with `header=0` (or omit the argument).

## Q2. Data Analysis – Five Highest Salaries

In [12]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

# Sort from highest salary to lowest and keep the first five records.
top_five = df.sort_values('Salary', ascending=False).head(5)

print(top_five)

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


**Issue:** Ascending sorting puts the lowest salaries first.  
**Correction:** Use `ascending=False` so the highest salaries come first, then select five rows.

## Q3. Cleaning Data – Missing Marks

In [13]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

# fillna() returns a filled Series, so assign it back to the DataFrame.
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


**Issue:** The original `fillna()` call did not store the returned result.  
**Correction:** Assign the filled values back to `df['Marks']`.

## Q4. Correlation

In [14]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

# Select the two Series and calculate their correlation.
correlation = df['Hours'].corr(df['Marks'])

print("Correlation:", correlation)

Correlation: 1.0


**Issue:** The original `DataFrame.corr()` call was given column names incorrectly.  
**Correction:** Select the two Series and call `Series.corr()`.

# Section C – Edge Cases

## Q1. NumPy Broadcasting

In [15]:
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

# Broadcasting expands the compatible dimensions during element-wise addition.
result = a + b

print(result)
print("Shape:", result.shape)

# These shapes are incompatible for broadcasting.
try:
    a + np.array([1, 2])
except ValueError as error:
    print("Error:", error)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
Shape: (3, 3)


**Explanation:** Shapes `(3, 1)` and `(1, 3)` broadcast to `(3, 3)`. A `(2,)` array cannot be aligned with the required dimensions, so NumPy raises a broadcasting error.

## Q2. CSV Parsing, Missing Values, and Dates

In [16]:
import pandas as pd
from io import StringIO

csv_data = '''ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA'''

# Quoted commas stay inside the Name field.
# Blank values and NA are treated as missing values for inspection.
df = pd.read_csv(
    StringIO(csv_data),
    na_values=['NA', ''],
    keep_default_na=True
)

# Convert the mixed date representations into datetime values.
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

print(df)
print("\nData types:")
print(df.dtypes)

    ID     Name       Date  Marks
0  101  Asha, R 2026-01-09   80.0
1  102     Ravi        NaT    NaN
2  103     Neha 2026-03-09    NaN

Data types:
ID                int64
Name             object
Date     datetime64[ns]
Marks           float64
dtype: object


**Explanation:** The quoted comma in `Asha, R` is handled correctly by CSV parsing. The blank and `NA` Marks values need investigation, and the Date column is converted to a datetime type for consistent analysis.

## Q3. Extreme Salary Value

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

# Locate the record with the highest salary for investigation.
highest_salary_record = df.loc[df["Salary"].idxmax()]

print("\nHighest salary record:")
print(highest_salary_record)

Mean: 2522500.0
Median: 32500.0

Highest salary record:
Employee           D
Salary      10000000
Name: 3, dtype: object


**Explanation:** The extreme salary increases the mean substantially, while the median remains resistant to the extreme value. The median better represents a typical salary here. The highest-salary record should be investigated before removal because it may be genuine.

# Section D – Scenario-Based Problems

## Q1. Student Assessment Data Cleaning

In [18]:
import pandas as pd
import numpy as np
from io import StringIO

csv_data = '''Student_ID,Student_Name,Department,Assessment,Marks
S101,Asha,IT,Python,85
S102,Ravi,it,Python,78
S103,Neha,I.T.,Python,92
S104,Karan,HR,Python,
S105,Meera,HR,Python,Absent
S106,Arjun,Finance,Python,0
S107,Priya,finance,Python,67
S108,Rahul,IT,Python,75
S102,Ravi,it,Python,78
S109,Sneha,I.T.,Python,NA
S110,Varun,HR,Python,88 marks
S111,Diya,Finance,Python,91
S112,Aman,IT,Python,
S113,Nisha,HR,Python,64
S114,Kabir,Finance,Python,105'''

# Load the dirty dataset.
df = pd.read_csv(StringIO(csv_data), keep_default_na=False)

print("First five rows:")
print(df.head())

print("\nData information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

First five rows:
  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python        
4       S105        Meera         HR     Python  Absent

Data information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Student_ID    15 non-null     object
 1   Student_Name  15 non-null     object
 2   Department    15 non-null     object
 3   Assessment    15 non-null     object
 4   Marks         15 non-null     object
dtypes: object(5)
memory usage: 732.0+ bytes

Missing values:
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           0
dtype: int64


**Explanation:** We first inspect the dataset before changing it. `head()`, `info()`, and `isnull().sum()` reveal its structure, data types, and missing values.

In [19]:
# Standardize department names so equivalent labels become consistent.
df['Department'] = (
    df['Department']
    .str.strip()
    .str.lower()
    .replace({
        'it': 'IT',
        'i.t.': 'IT',
        'finance': 'Finance',
        'hr': 'HR'
    })
)

# Remove exact duplicate assessment records.
before = len(df)
df = df.drop_duplicates()
duplicates_removed = before - len(df)

print("Duplicates removed:", duplicates_removed)
print("\nStandardized departments:")
print(sorted(df['Department'].unique()))

Duplicates removed: 1

Standardized departments:
['Finance', 'HR', 'IT']


**Explanation:** Standardizing labels prevents the same department from being treated as multiple groups. Exact duplicate rows are removed and the number removed is recorded.

In [20]:
# Keep track of whether the original value represented an absence.
df['Attendance_Status'] = np.where(
    df['Marks'].astype(str).str.strip().str.lower().eq('absent'),
    'Absent',
    'Recorded'
)

# Extract numeric marks such as 88 from "88 marks".
# Values such as blank, NA, and Absent become NaN.
df['Marks'] = (
    df['Marks']
    .astype(str)
    .str.extract(r'(\d+(?:\.\d+)?)', expand=False)
    .astype(float)
)

print(df[['Student_ID', 'Student_Name', 'Marks', 'Attendance_Status']])

   Student_ID Student_Name  Marks Attendance_Status
0        S101         Asha   85.0          Recorded
1        S102         Ravi   78.0          Recorded
2        S103         Neha   92.0          Recorded
3        S104        Karan    NaN          Recorded
4        S105        Meera    NaN            Absent
5        S106        Arjun    0.0          Recorded
6        S107        Priya   67.0          Recorded
7        S108        Rahul   75.0          Recorded
9        S109        Sneha    NaN          Recorded
10       S110        Varun   88.0          Recorded
11       S111         Diya   91.0          Recorded
12       S112         Aman    NaN          Recorded
13       S113        Nisha   64.0          Recorded
14       S114        Kabir  105.0          Recorded


**Explanation:** Numeric marks are extracted from text values, while `Absent`, `NA`, and blank values remain unavailable for numerical analysis. Absence is kept as a separate status instead of silently converting it to zero.

In [21]:
# Investigate missing marks separately.
missing_records = df[df['Marks'].isna()]

print("Missing/unavailable marks:")
print(missing_records[['Student_ID', 'Student_Name', 'Marks', 'Attendance_Status']])

# Identify marks outside the valid assessment range.
invalid_records = df[(df['Marks'] < 0) | (df['Marks'] > 100)]

print("\nInvalid marks outside 0-100:")
print(invalid_records[['Student_ID', 'Student_Name', 'Marks']])

Missing/unavailable marks:
   Student_ID Student_Name  Marks Attendance_Status
3        S104        Karan    NaN          Recorded
4        S105        Meera    NaN            Absent
9        S109        Sneha    NaN          Recorded
12       S112         Aman    NaN          Recorded

Invalid marks outside 0-100:
   Student_ID Student_Name  Marks
14       S114        Kabir  105.0


**Explanation:** Missing values are investigated instead of being deleted immediately. Marks outside 0–100 are flagged as invalid and require review before any removal or correction.

In [22]:
# Label each record so the cleaning result remains transparent.
df['Mark_Status'] = np.select(
    [
        df['Marks'].isna(),
        (df['Marks'] < 0) | (df['Marks'] > 100)
    ],
    [
        'Missing/Unavailable',
        'Invalid'
    ],
    default='Valid'
)

print("Cleaned DataFrame:")
print(df)

print("\nFinal summary:")
print("Records removed:", duplicates_removed)
print("Missing marks remaining:", int(df['Marks'].isna().sum()))
print("Invalid marks identified:", int(((df['Marks'] < 0) | (df['Marks'] > 100)).sum()))

Cleaned DataFrame:
   Student_ID Student_Name Department Assessment  Marks Attendance_Status  \
0        S101         Asha         IT     Python   85.0          Recorded   
1        S102         Ravi         IT     Python   78.0          Recorded   
2        S103         Neha         IT     Python   92.0          Recorded   
3        S104        Karan         HR     Python    NaN          Recorded   
4        S105        Meera         HR     Python    NaN            Absent   
5        S106        Arjun    Finance     Python    0.0          Recorded   
6        S107        Priya    Finance     Python   67.0          Recorded   
7        S108        Rahul         IT     Python   75.0          Recorded   
9        S109        Sneha         IT     Python    NaN          Recorded   
10       S110        Varun         HR     Python   88.0          Recorded   
11       S111         Diya    Finance     Python   91.0          Recorded   
12       S112         Aman         IT     Python    NaN  

**Explanation:** The final result keeps the cleaning decisions visible. This makes the dataset easier to audit and prevents meaningful cases such as absence from being confused with an ordinary missing entry.